# fly.toml app configuration file generated for essnine-devsite on 2025-02-05T14:08:29Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'essnine-devsite'
primary_region = 'ams'
kill_signal = 'SIGINT'
kill_timeout = '5s'

[experimental]
  auto_rollback = true

[build]

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[services]]
  protocol = 'tcp'
  internal_port = 80
  processes = ['app']

  [[services.ports]]
    port = 80
    handlers = ['http']
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ['tls', 'http']

  [services.concurrency]
    type = 'connections'
    hard_limit = 25
    soft_limit = 20

  [[services.http_checks]]
    interval = '15s'
    timeout = '2s'
    grace_period = '1s'
    method = 'get'
    path = '/'

[[vm]]
  size = 'shared-cpu-1x'
